#!D:\Projects\MLOps_End_to_End_Project\MLOPS_END_TO_END_PROJECT\mlops_env\python.exe
# -*- coding: UTF-8 -*-
from __future__ import print_function, division, absolute_import

from numba.misc.numba_entry import main

if __name__ == "__main__":
    main()
